# Variables needed for this script are:

# Case 1: Stored on Travis Settings
  #For dev environment:
    # - AWS_ACCOUNT_USER_ID_DEV
    # - AWS_ACCOUNT_SECRET_DEV
    # - AWS_PROFILE_DEV

  #For Demo environment:
    # - AWS_ACCOUNT_USER_ID_DEMO
    # - AWS_ACCOUNT_SECRET_DEMO
    # - AWS_PROFILE_DEMO

  #For Prod environment:
    # - AWS_ACCOUNT_USER_ID_PROD
    # - AWS_ACCOUNT_SECRET_PROD
    # - AWS_PROFILE_PROD

# Case 2: Created when Travis CI runs ??
    # - TRAVIS_TAG
    # - TRAVIS_OS_NAME
sudo: required
language: go

before_install:
  - curl -sf https://up.apex.sh/install | sudo sh
  - sudo up upgrade
  - pip install --user awscli
  - aws configure set profile.${AWS_PROFILE_DEV}.aws_access_key_id $AWS_ACCOUNT_USER_ID_DEV
  - aws configure set profile.${AWS_PROFILE_DEV}.aws_secret_access_key $AWS_ACCOUNT_SECRET_DEV
  - aws configure set profile.${AWS_PROFILE_DEV}.region $AWS_DEFAULT_REGION

install:
  - go get -t ./...
  - sudo apt-get install jq -y

# script:
#   - go test -v ./...

deploy:
  # dev
  - provider: script
    script: TRAVIS_PROFILE=$AWS_PROFILE_DEV TRAVIS_AWS_ACCESS_KEY_ID=$AWS_ACCOUNT_USER_ID_DEV TRAVIS_AWS_SECRET_ACCESS_KEY=$AWS_ACCOUNT_SECRET_DEV TRAVIS_AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION ./deploy.sh dev
    on:
      branch: remove_hard_coded_variables
  # dev
  - provider: script
    script: TRAVIS_PROFILE=$AWS_PROFILE_DEV TRAVIS_AWS_ACCESS_KEY_ID=$AWS_ACCOUNT_USER_ID_DEV TRAVIS_AWS_SECRET_ACCESS_KEY=$AWS_ACCOUNT_SECRET_DEV TRAVIS_AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION ./deploy.sh dev
    on:
      tags: true
      branch: master
  # dev
  - provider: script
    script: TRAVIS_PROFILE=$AWS_PROFILE_DEV TRAVIS_AWS_ACCESS_KEY_ID=$AWS_ACCOUNT_USER_ID_DEV TRAVIS_AWS_SECRET_ACCESS_KEY=$AWS_ACCOUNT_SECRET_DEV TRAVIS_AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION ./deploy.sh dev
    on:
      tags: true
      branch: master
env:
  - GO111MODULE=on
