sudo: required
language: go
go:
- tip
before_install:
- curl -sf https://up.apex.sh/install | sudo sh
- sudo up upgrade
install:
- go get -t ./...
- sudo apt-get install jq -y
script:
- go test -v ./...
deploy:
 # dev
 - provider: script
   script: make
   skip_cleanup: true
   on:
      branch: master
 # demo
 - provider: script
   script: AWS_ACCESS_KEY_ID=$AWS_915001051872_ID AWS_SECRET_ACCESS_KEY=$AWS_915001051872_SECRET make demo
   skip_cleanup: true
   on:
      branch: master
 # production
 - provider: script
   script: AWS_ACCESS_KEY_ID=$AWS_192458993663_ID AWS_SECRET_ACCESS_KEY=$AWS_192458993663_SECRET make prod
   skip_cleanup: true
   on:
      branch: master
